### PR TITLE
FIX: ViewStyle Defaults

### LINKED ISSUE #43: ViewStyle overwrites tintColor, backgroundColor and alpha if set in IB

### PR DESCRIPTION
**Pull request by jakubpetrik**
fixes #43

### CODE REVIEW

File: Styles/Classes/UIElement+Extensions/UITextField+Styles.m [hunk 1]
```diff
@@ -96,11 +96,30 @@ - (void)setPlaceholderStyle:(TextStyle *)style forState:(TextInputState)state {
...
+    NSError *error = nil;
+
+    [editing hasEqualLayerProperties:inactive error:&error];
+
+    if (error) {
+        NSAssert(NO, @"Invalid layer configuration for %@. %@", [self class], [error localizedDescription]);
+    }
+}
+
+
```
Comment (radimhalfar) [inline Styles/Classes/UIElement+Extensions/UITextField+Styles.m]: xtra line
